language: julia
os:
    - linux
    - osx
julia:
    - 1.4
    # - nightly
    
branches:
  only:
    - master
    - dev
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # build tagged releases
env:
    global:
    - PYTHON=conda
    # matrix:
    # - MPMATH=true
    # - MPMATH=false
before_install:
    #install mpmath to test functionality
#   - if [ $MPMATH = "true" ]; then julia -e 'using Pkg; Pkg.add("Conda"); using Conda; Conda.add("mpmath")';fi
after_success:
- julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'


jobs:
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --depwarn=no --project=docs/ docs/make.jl
      after_success: skip
