[[AbstractFFTs]]
deps = ["Compat", "LinearAlgebra"]
git-tree-sha1 = "8d59c3b1463b5e0ad05a3698167f85fac90e184d"
uuid = "621f4979-c628-5d54-868e-fcf4e3e8185c"
version = "0.3.2"

[[Arpack]]
deps = ["BinaryProvider", "Libdl", "LinearAlgebra", "Random", "SparseArrays", "Test"]
git-tree-sha1 = "5b046410fb617d9cf2f8bc0edd5da05a2e5a2ad4"
uuid = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
version = "0.2.3"

[[AxisAlgorithms]]
deps = ["Compat", "WoodburyMatrices"]
git-tree-sha1 = "99dabbe853e4f641ab21a676131f2cf9fb29937e"
uuid = "13072b0f-2c55-5437-9ae7-d433b7a33950"
version = "0.3.0"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BinDeps]]
deps = ["Compat", "Libdl", "SHA", "URIParser"]
git-tree-sha1 = "12093ca6cdd0ee547c39b1870e0c9c3f154d9ca9"
uuid = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
version = "0.8.10"

[[BinaryProvider]]
deps = ["Libdl", "Pkg", "SHA", "Test"]
git-tree-sha1 = "b530fbeb6f41ab5a83fbe3db1fcbe879334bcd2d"
uuid = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
version = "0.4.2"

[[BufferedStreams]]
deps = ["Compat", "Pkg", "Test"]
git-tree-sha1 = "5d55b9486590fdda5905c275bb21ce1f0754020f"
uuid = "e1450e63-4bb3-523b-b2a4-4ffa8c0fd77d"
version = "1.0.0"

[[Cairo]]
deps = ["BinDeps", "Colors", "Compat", "Graphics", "Homebrew", "Libdl", "Pkg", "WinRPM"]
git-tree-sha1 = "42cf9b32ef7841106f4b11b2163fc12351d1c32d"
uuid = "159f3aea-2a34-519c-b102-8c37f9878175"
version = "0.5.5"

[[Calculus]]
deps = ["Compat"]
git-tree-sha1 = "f60954495a7afcee4136f78d1d60350abd37a409"
uuid = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
version = "0.4.1"

[[CategoricalArrays]]
deps = ["Compat", "Future", "JSON", "Missings", "Printf", "Reexport"]
git-tree-sha1 = "8009a507e2e3db040d6854a82ce959fb5971cb37"
uuid = "324d7699-5711-5eae-9e2f-1d82baa6b597"
version = "0.3.13"

[[CodecZlib]]
deps = ["BinaryProvider", "Libdl", "Pkg", "Test", "TranscodingStreams"]
git-tree-sha1 = "83cb3d65c37ea1364c2d5bf7bcea41843ba645dc"
uuid = "944b1d66-785c-5afd-91f1-9de20f533193"
version = "0.5.0"

[[ColorTypes]]
deps = ["FixedPointNumbers", "Random", "Test"]
git-tree-sha1 = "0e3209ba7418aed732e5c3818076b4400ee36c08"
uuid = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
version = "0.7.4"

[[Colors]]
deps = ["ColorTypes", "FixedPointNumbers", "InteractiveUtils", "Pkg", "Printf", "Reexport", "Test"]
git-tree-sha1 = "8c89e0a9a583954eae3efcf6a531e51c02b38cee"
uuid = "5ae59095-9a9b-59fe-a467-6f913c188581"
version = "0.9.4"

[[CommonSubexpressions]]
deps = ["Test"]
git-tree-sha1 = "efdaf19ab11c7889334ca247ff4c9f7c322817b0"
uuid = "bbf7d656-a473-5ed7-a52c-81e309532950"
version = "0.2.0"

[[Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "Serialization", "SharedArrays", "Sockets", "SparseArrays", "Statistics", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "ae262fa91da6a74e8937add6b613f58cd56cdad4"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "1.1.0"

[[Compose]]
deps = ["Colors", "Compat", "DataStructures", "IterTools", "JSON", "Measures"]
git-tree-sha1 = "9a77c574fd4b05a818be68f7781dcea8f8965181"
uuid = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
version = "0.6.1"

[[Conda]]
deps = ["Compat", "JSON", "VersionParsing"]
git-tree-sha1 = "a47f9a2c7b80095e6a935536795635522fe27f5d"
uuid = "8f4d0f93-b110-5947-807f-2305c1781a2d"
version = "1.0.1"

[[Contour]]
deps = ["LinearAlgebra", "StaticArrays", "Test"]
git-tree-sha1 = "b974e164358fea753ef853ce7bad97afec15bb80"
uuid = "d38c429a-6771-53c6-b99e-75d170b6e991"
version = "0.5.1"

[[CoupledFields]]
deps = ["Compat", "StatsBase"]
git-tree-sha1 = "d56f26542bb7af9c0ec16e098a0a33352f3c9d8e"
uuid = "7ad07ef1-bdf2-5661-9d2b-286fd4296dac"
version = "0.1.0"

[[DataArrays]]
deps = ["Missings", "Reexport", "SpecialFunctions", "StatsBase"]
git-tree-sha1 = "494cb14e8ca5912ded3652f11f9e67914c437a47"
uuid = "0fe7c1db-08c2-54a3-a222-6d1d3b7a471a"
version = "0.7.0"

[[DataFrames]]
deps = ["CategoricalArrays", "CodecZlib", "Compat", "DataStreams", "Dates", "InteractiveUtils", "LinearAlgebra", "Missings", "Pkg", "Printf", "Random", "Reexport", "SortingAlgorithms", "Statistics", "StatsBase", "Test", "TranscodingStreams", "Unicode", "WeakRefStrings"]
git-tree-sha1 = "31cca86a48add8d5cdd9457c4f75ee5577ef3488"
uuid = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
version = "0.13.1"

[[DataStreams]]
deps = ["Dates", "Missings", "Test", "WeakRefStrings"]
git-tree-sha1 = "c54fb051465fb0741caa57972b67bd21ce2f39c7"
uuid = "9a8bc11e-79be-5b39-94d7-1ccc349a1a85"
version = "0.4.0"

[[DataStructures]]
deps = ["InteractiveUtils", "REPL", "Random", "Serialization", "Test"]
git-tree-sha1 = "2afbbd0294306b0b74a753c196be50b35edb625c"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.11.1"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelimitedFiles]]
deps = ["Mmap"]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[DiffEqDiffTools]]
deps = ["LinearAlgebra", "Test"]
git-tree-sha1 = "9c7a902a53542b5b3178a2ed16878bda02685456"
uuid = "01453d9d-ee7c-5054-8395-0335cb756afa"
version = "0.6.0"

[[DiffResults]]
deps = ["Compat", "StaticArrays"]
git-tree-sha1 = "db8acf46717b13d6c48deb7a12007c7f85a70cf7"
uuid = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
version = "0.0.3"

[[DiffRules]]
deps = ["Random", "Test"]
git-tree-sha1 = "c49ec69428ffea0c1d1bbdc63d1a70f5df5860ad"
uuid = "b552c78f-8df3-52c6-915a-8e097449b14b"
version = "0.0.7"

[[Distances]]
deps = ["LinearAlgebra", "Pkg", "Printf", "Random", "Statistics", "Test"]
git-tree-sha1 = "2f38605722542f1c0a32dd2856fb529d8c226c69"
uuid = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
version = "0.7.3"

[[Distributed]]
deps = ["LinearAlgebra", "Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[Distributions]]
deps = ["Distributed", "LinearAlgebra", "PDMats", "Printf", "QuadGK", "Random", "SpecialFunctions", "Statistics", "StatsBase", "StatsFuns", "Test"]
git-tree-sha1 = "c43dc10a52598ad76d61f8907b3b30f159ca146f"
uuid = "31c24e10-a181-5473-b8eb-7969acd0382f"
version = "0.16.2"

[[FFTW]]
deps = ["AbstractFFTs", "BinaryProvider", "Compat", "Conda", "Libdl", "LinearAlgebra", "Pkg", "Reexport", "Test"]
git-tree-sha1 = "29cda58afbf62f35b1a094882ad6c745a47b2eaa"
uuid = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
version = "0.2.4"

[[FileWatching]]
uuid = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"

[[FixedPointNumbers]]
deps = ["Pkg", "Test"]
git-tree-sha1 = "31cbf24d537a217475b37274df05de09882b53f1"
uuid = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
version = "0.5.2"

[[ForwardDiff]]
deps = ["CommonSubexpressions", "DiffResults", "DiffRules", "InteractiveUtils", "LinearAlgebra", "NaNMath", "Pkg", "Random", "SparseArrays", "SpecialFunctions", "StaticArrays", "Test"]
git-tree-sha1 = "0dd11038da4efce9ce457b1cf47a52eaf6251bd3"
uuid = "f6369f11-7733-5829-9624-2563aa707210"
version = "0.8.5"

[[Future]]
deps = ["Random"]
uuid = "9fa8497b-333b-5362-9e8d-4d0656e87820"

[[Gadfly]]
deps = ["Colors", "Compat", "Compose", "Contour", "CoupledFields", "DataArrays", "DataFrames", "DataStructures", "Distributions", "Hexagons", "IndirectArrays", "IterTools", "JSON", "Juno", "KernelDensity", "Loess", "Missings", "Showoff", "StatsBase", "WeakRefStrings"]
git-tree-sha1 = "94219679de9245fcda87d03534f531519ecee2e6"
uuid = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
version = "0.7.0"

[[Graphics]]
deps = ["Colors", "Compat", "NaNMath"]
git-tree-sha1 = "4671f2427ea4494a5d14fd485c4aa61ec1fb7cd2"
uuid = "a2bd30eb-e257-5431-a919-1863eab51364"
version = "0.3.0"

[[HTTPClient]]
deps = ["Compat", "LibCURL"]
git-tree-sha1 = "161d5776ae8e585ac0b8c20fb81f17ab755b3671"
uuid = "0862f596-cf2d-50af-8ef4-f2be67dfa83f"
version = "0.2.1"

[[Hexagons]]
deps = ["Compat"]
git-tree-sha1 = "3e05eb6008bd019a430733d246f7ff0837c8c6ef"
uuid = "a1b4810d-1bce-5fbd-ac56-80944d57a21f"
version = "0.1.0"

[[Homebrew]]
deps = ["BinDeps", "InteractiveUtils", "JSON", "Libdl", "Test", "Unicode"]
git-tree-sha1 = "5582ec74f735cf8d12e562a2e65c47f34063bd51"
uuid = "d9be37ee-ecc9-5288-90f1-b9ca67657a75"
version = "0.7.0"

[[IJulia]]
deps = ["Compat", "Conda", "InteractiveUtils", "JSON", "Markdown", "MbedTLS", "Pkg", "REPL", "Random", "SoftGlobalScope", "UUIDs", "ZMQ"]
git-tree-sha1 = "def2e9ee9963ee935dab64fb0d971042c384dbfd"
uuid = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
version = "1.10.0"

[[IndirectArrays]]
deps = ["Compat", "Pkg", "Test"]
git-tree-sha1 = "b6e249be10a3381b2c72ac82f2d13d70067cb2bd"
uuid = "9b13fd28-a010-5f03-acff-a1bbcff69959"
version = "0.5.0"

[[InteractiveUtils]]
deps = ["LinearAlgebra", "Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[Interpolations]]
deps = ["AxisAlgorithms", "Compat", "LinearAlgebra", "OffsetArrays", "Ratios", "ShowItLikeYouBuildIt", "WoodburyMatrices"]
git-tree-sha1 = "da2709d9f94b0ebd3da2c7cb92a1ce1e0d807913"
uuid = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
version = "0.8.0"

[[IterTools]]
deps = ["Pkg", "SparseArrays", "Test"]
git-tree-sha1 = "ed0787e62dc46b8d8c7c3db54391d71e0da5fefd"
uuid = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
version = "1.0.0"

[[Iterators]]
git-tree-sha1 = "6b5a31f893d8453ce65da5e8c25b9e125d1cdfa5"
uuid = "a4bce56a-f44e-563f-a45f-5312daf41243"
version = "0.3.1"

[[JSON]]
deps = ["Dates", "Distributed", "Mmap", "Pkg", "Sockets", "Test", "Unicode"]
git-tree-sha1 = "fec8e4d433072731466d37ed0061b3ba7f70eeb9"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.19.0"

[[Juno]]
deps = ["Base64", "Logging", "Media", "Profile", "Test"]
git-tree-sha1 = "f2d553719755f00f602cb226689c0bcfee023a1d"
uuid = "e5e0dc1b-0480-54bc-9374-aad01c23163d"
version = "0.5.2"

[[KernelDensity]]
deps = ["Distributions", "FFTW", "Interpolations", "Optim", "Pkg", "StatsBase", "Test"]
git-tree-sha1 = "45265e5cc77bff050db33bdcb2d34e00630abfd6"
uuid = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
version = "0.5.0"

[[LibCURL]]
deps = ["BinaryProvider", "Compat", "Libdl", "Pkg"]
git-tree-sha1 = "13cace3a2a2e76de68024c0b2c1a1bf00ee81b88"
uuid = "b27032c2-a3e7-50c8-80cd-2d36dbcbfd21"
version = "0.3.2"

[[LibExpat]]
deps = ["Compat", "Pkg"]
git-tree-sha1 = "fde352ec13479e2f90e57939da2440fb78c5e388"
uuid = "522f3ed2-3f36-55e3-b6df-e94fee9b0c07"
version = "0.5.0"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[Libz]]
deps = ["BufferedStreams", "Random", "Test"]
git-tree-sha1 = "d405194ffc0293c3519d4f7251ce51baac9cc871"
uuid = "2ec943e9-cfe8-584d-b93d-64dcb6d567b7"
version = "1.0.0"

[[LightGraphs]]
deps = ["Arpack", "Base64", "CodecZlib", "DataStructures", "DelimitedFiles", "Distributed", "LinearAlgebra", "Markdown", "Pkg", "Random", "SharedArrays", "SimpleTraits", "SparseArrays", "Statistics", "Test"]
git-tree-sha1 = "fd35b52d1e347e71dfec1e2bf5dbc7d5a46db8ec"
uuid = "093fc24a-ae57-5d10-9952-331d41423f4d"
version = "1.0.2"

[[LineSearches]]
deps = ["LinearAlgebra", "NLSolversBase", "NaNMath", "Parameters", "Printf", "Test"]
git-tree-sha1 = "31d89c1b2594d741cb78f5fc7cb616762a71b559"
uuid = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
version = "7.0.0"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Loess]]
deps = ["Distances", "Random", "Statistics", "Test"]
git-tree-sha1 = "0ee46caf683a422b595be4dfaed6cda28f541e25"
uuid = "4345ca2d-374a-55d4-8d30-97f9976e7612"
version = "0.5.0"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[MacroTools]]
deps = ["Compat"]
git-tree-sha1 = "c443e1c8d58a4e9f61b708ad0a88286c7042145b"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.4.4"

[[Mamba]]
deps = ["Cairo", "Calculus", "Compose", "Distributions", "Gadfly", "LightGraphs", "PDMats", "Showoff", "StatsBase"]
git-tree-sha1 = "30982a64f10587a2e4ef0af8db69bfb6627c6503"
uuid = "5424a776-8be3-5c5b-a13f-3551f69ba0e6"
version = "0.11.2"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[MbedTLS]]
deps = ["BinaryProvider", "Compat", "Libdl", "Pkg", "Sockets"]
git-tree-sha1 = "17d5a81dbb1e682d4ff707c01f0afe5948068fa6"
uuid = "739be429-bea8-5141-9913-cc70e7f3736d"
version = "0.6.0"

[[Measures]]
deps = ["Compat"]
git-tree-sha1 = "9cdd05418a7f2f7ce534014285edf01f465d6961"
uuid = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
version = "0.2.0"

[[Media]]
deps = ["MacroTools", "Test"]
git-tree-sha1 = "9f390271c9a43dcbe908a10b5b9632cf58cbab5b"
uuid = "e89f7d12-3494-54d1-8411-f7d8b9ae1f27"
version = "0.4.1"

[[Missings]]
deps = ["Compat"]
git-tree-sha1 = "866fb034899be6055dcb6cb1a70fbda379bb0b55"
uuid = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
version = "0.2.10"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[NLSolversBase]]
deps = ["Calculus", "DiffEqDiffTools", "DiffResults", "Distributed", "ForwardDiff", "LinearAlgebra", "Random", "SparseArrays", "Test"]
git-tree-sha1 = "75f08d4dd9174855aefe4dc9532569450bffcd93"
uuid = "d41bc354-129a-5804-8e4c-c37616107c6c"
version = "7.1.0"

[[NaNMath]]
deps = ["Compat"]
git-tree-sha1 = "ce3b85e484a5d4c71dd5316215069311135fa9f2"
uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
version = "0.3.2"

[[OffsetArrays]]
deps = ["DelimitedFiles", "Test"]
git-tree-sha1 = "f8cd140824f74f2948ff8660bc2292e16d29c1b7"
uuid = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
version = "0.8.1"

[[Optim]]
deps = ["Calculus", "Compat", "DiffEqDiffTools", "ForwardDiff", "LineSearches", "LinearAlgebra", "NLSolversBase", "NaNMath", "Parameters", "Pkg", "PositiveFactorizations", "Printf", "Random", "SparseArrays", "StatsBase", "Test"]
git-tree-sha1 = "0ed8809e72d3b595930c8ade539838a99f94dc8b"
uuid = "429524aa-4258-5aef-a3af-852621145aeb"
version = "0.16.0"

[[PDMats]]
deps = ["Arpack", "LinearAlgebra", "SparseArrays", "SuiteSparse", "Test"]
git-tree-sha1 = "9e3e7a5c9b8cfdba8c01a1bcae38fe0144936fda"
uuid = "90014a1f-27ba-587c-ab20-58faa44d9150"
version = "0.9.5"

[[Parameters]]
deps = ["Compat", "DataStructures", "REPL"]
git-tree-sha1 = "9554e6665968d1ff6f5342b188475163b05e527d"
uuid = "d96e819e-fc66-5662-9728-84c9c7592b0a"
version = "0.9.2"

[[Pkg]]
deps = ["Dates", "LibGit2", "Markdown", "Printf", "REPL", "Random", "SHA", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[PositiveFactorizations]]
deps = ["LinearAlgebra", "Test"]
git-tree-sha1 = "86ae7329c4b5c266acf5c7c524a972300d991e1c"
uuid = "85a6dd25-e78a-55b7-8502-1745935b8125"
version = "0.2.1"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[Profile]]
deps = ["Printf"]
uuid = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"

[[QuadGK]]
deps = ["DataStructures", "LinearAlgebra", "Test"]
git-tree-sha1 = "7d61ca207f021be6574b365a1a077bea04935f19"
uuid = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
version = "2.0.1"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Ratios]]
deps = ["Compat"]
git-tree-sha1 = "fd159bead0a24e6270fd0573a340312bd4645cc2"
uuid = "c84ed2f1-dad5-54f0-aa8e-dbefe2724439"
version = "0.3.0"

[[Reexport]]
deps = ["Pkg"]
git-tree-sha1 = "7b1d07f411bc8ddb7977ec7f377b97b158514fe0"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "0.2.0"

[[Rmath]]
deps = ["BinaryProvider", "Libdl", "Pkg", "Random", "Statistics", "Test"]
git-tree-sha1 = "9a6c758cdf73036c3239b0afbea790def1dabff9"
uuid = "79098fc4-a85e-5d69-aa6a-4863f24498fa"
version = "0.5.0"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SharedArrays]]
deps = ["Distributed", "Mmap", "Random", "Serialization"]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[ShowItLikeYouBuildIt]]
git-tree-sha1 = "e562bce4b0df3ed65562ce2ec7f56cb399368daf"
uuid = "9966252f-7483-59e3-9a4c-8607a6b2a5fe"
version = "0.2.0"

[[Showoff]]
deps = ["Compat", "Pkg"]
git-tree-sha1 = "276b24f3ace98bec911be7ff2928d497dc759085"
uuid = "992d4aef-0814-514b-bc4d-f2e9a6c4116f"
version = "0.2.1"

[[SimpleTraits]]
deps = ["InteractiveUtils", "MacroTools", "Pkg", "Test"]
git-tree-sha1 = "c0a542b8d5e369b179ccd296b2ca987f6da5da0a"
uuid = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
version = "0.8.0"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SoftGlobalScope]]
deps = ["Test"]
git-tree-sha1 = "9864735a12405284e5bdeafd15617dd72c50b6be"
uuid = "b85f4697-e234-5449-a836-ec8e2f98b302"
version = "1.0.1"

[[SortingAlgorithms]]
deps = ["DataStructures", "Random", "Test"]
git-tree-sha1 = "03f5898c9959f8115e30bc7226ada7d0df554ddd"
uuid = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
version = "0.3.1"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[SpecialFunctions]]
deps = ["BinDeps", "BinaryProvider", "Compat", "Libdl"]
git-tree-sha1 = "d12f8917be3782f4b800ba16003b8d0d4858c2e5"
uuid = "276daf66-3868-5448-9aa4-cd146d93841b"
version = "0.7.0"

[[StaticArrays]]
deps = ["InteractiveUtils", "LinearAlgebra", "Random", "Statistics", "Test"]
git-tree-sha1 = "d432c79bef174a830304f8601427a4357dfdbfb7"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "0.8.3"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[StatsBase]]
deps = ["DataStructures", "LinearAlgebra", "Missings", "Printf", "Random", "SortingAlgorithms", "SparseArrays", "Statistics", "Test"]
git-tree-sha1 = "723193a13e8078cec6dcd0b8fe245c8bfd81690e"
uuid = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
version = "0.25.0"

[[StatsFuns]]
deps = ["Pkg", "Rmath", "SpecialFunctions", "Test"]
git-tree-sha1 = "d14bb7b03defd2deaa5675646f6783089e0556f0"
uuid = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
version = "0.7.0"

[[SuiteSparse]]
deps = ["Libdl", "LinearAlgebra", "SparseArrays"]
uuid = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[TranscodingStreams]]
deps = ["DelimitedFiles", "Pkg", "Random", "Test"]
git-tree-sha1 = "a34a2d588e2d2825602bf14a24216d5c8b0921ec"
uuid = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
version = "0.8.1"

[[URIParser]]
deps = ["Test", "Unicode"]
git-tree-sha1 = "6ddf8244220dfda2f17539fa8c9de20d6c575b69"
uuid = "30578b45-9adc-5946-b283-645ec420af67"
version = "0.4.0"

[[UUIDs]]
deps = ["Random"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[VersionParsing]]
deps = ["Compat"]
git-tree-sha1 = "c9d5aa108588b978bd859554660c8a5c4f2f7669"
uuid = "81def892-9a0e-5fdd-b105-ffc91e053289"
version = "1.1.2"

[[WeakRefStrings]]
deps = ["Missings", "Random", "Test"]
git-tree-sha1 = "d4631352d65840254d33ab703e2de3d9768cdb77"
uuid = "ea10d353-3f73-51f8-a26c-33c1cb351aa5"
version = "0.5.2"

[[WinRPM]]
deps = ["BinDeps", "Compat", "HTTPClient", "LibExpat", "Libdl", "Libz", "SHA", "URIParser"]
git-tree-sha1 = "3ff6d7ad07dc216d5fc8e70ac994a6d6bb46347c"
uuid = "c17dfb99-b4f7-5aad-8812-456da1ad7187"
version = "0.4.1"

[[WoodburyMatrices]]
deps = ["LinearAlgebra", "Random", "SparseArrays", "Test"]
git-tree-sha1 = "21772c33b447757ec7d3e61fcdfb9ea5c47eedcf"
uuid = "efce3f68-66dc-5838-9240-27a6d6f5f9b6"
version = "0.4.1"

[[ZMQ]]
deps = ["BinaryProvider", "Compat", "FileWatching", "Libdl"]
git-tree-sha1 = "e9ced094bc2913c533db33283084f85e2a460465"
uuid = "c2297ded-f4af-51ae-bb23-16f91089e4e1"
version = "0.6.4"
