name = "Soss"
uuid = "8ce77f84-9b61-11e8-39ff-d17a774bf41c"
author = ["Chad Scherrer <chad.scherrer@gmail.com>"]
version = "0.15.5"

[deps]
AdvancedHMC = "0bf59076-c3b1-5ca4-86bd-e02cd72cde3d"
Bijectors = "76274a88-744f-5084-9051-94815aaf08c4"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DistributionsAD = "ced4e74d-a319-5a8a-b0ac-84af2272839c"
DynamicHMC = "bbc10e6e-7c05-544b-b16e-64fede858acb"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GeneralizedGenerated = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
MonteCarloMeasurements = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SimpleGraphs = "55797a34-41de-5266-9ec1-32ac4eb504d3"
SimplePartitions = "ec83eff0-a5b5-5643-ae32-5cbf6eedec9d"
SimplePosets = "b2aef97b-4721-5af9-b440-0bad754dc5ba"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
TransformVariables = "84d833dd-6860-57f9-a1a7-6da5db126cff"

[compat]
AdvancedHMC = "0.2"
Bijectors = "0.8"
CategoricalArrays = "0.8"
DiffResults = "1.0"
Distributions = "0.21, 0.22, 0.23, 0.24"
DistributionsAD = "0.6"
DynamicHMC = "2.1"
FillArrays = "0.8, 0.9, 0.10"
ForwardDiff = "0.10"
GeneralizedGenerated = "0.2"
Graphs = "0.10"
IterTools = "1.3"
LazyArrays = "0.14, 0.15, 0.16, 0.17, 0.18"
LogDensityProblems = "0.10"
MLStyle = "0.3, 0.4"
MacroTools = "0.5"
MappedArrays = "0.3"
MonteCarloMeasurements = "0.6,0.7, 0.8, 0.9"
NamedTupleTools = "0.12, 0.13"
RecipesBase = "0.7,0.8, 1.0"
Reexport = "0.2"
Requires = "1.0"
ReverseDiff = "1.0"
Setfield = "0.6, 0.7"
SimpleGraphs = "0.3, 0.4, 0.5, 0.6, 0.7"
SimplePartitions = "0.2, 0.3"
SimplePosets = "0.0, 0.1"
SpecialFunctions = "0.10"
StatsFuns = "0.9"
TransformVariables = "0.3"
julia = "1.4"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Documenter", "Literate", "Plots", "Random", "StableRNGs", "Test"]
