name = "Soss"
uuid = "8ce77f84-9b61-11e8-39ff-d17a774bf41c"
author = ["Chad Scherrer <chad.scherrer@gmail.com>"]
version = "0.11.0"

[deps]
AdvancedHMC = "0bf59076-c3b1-5ca4-86bd-e02cd72cde3d"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DynamicHMC = "bbc10e6e-7c05-544b-b16e-64fede858acb"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GeneralizedGenerated = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MonteCarloMeasurements = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
ResumableFunctions = "c5292f4c-5179-55e1-98c5-05642aab7184"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
SimpleGraphs = "55797a34-41de-5266-9ec1-32ac4eb504d3"
SimplePartitions = "ec83eff0-a5b5-5643-ae32-5cbf6eedec9d"
SimplePosets = "b2aef97b-4721-5af9-b440-0bad754dc5ba"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
TransformVariables = "84d833dd-6860-57f9-a1a7-6da5db126cff"

[compat]
AdvancedHMC = "0.2"
DiffResults = "1.0"
Distributions = "0.21, 0.22, 0.23"
DynamicHMC = "2.1"
FillArrays = "0.8"
ForwardDiff = "0.10"
GeneralizedGenerated = "0.2"
Graphs = "0.10"
IterTools = "1.3"
LazyArrays = "0.14, 0.15"
LogDensityProblems = "0.10"
MLStyle = "0.3"
MacroTools = "0.5"
MonteCarloMeasurements = "0.6,0.7, 0.8"
NamedTupleTools = "0.12, 0.13"
PyCall = "1.91"
RecipesBase = "0.7,0.8"
Reexport = "0.2"
ResumableFunctions = "0.5"
ReverseDiff = "1.0"
SimpleGraphs = "0.3"
SimplePartitions = "0.2"
SimplePosets = "0.0"
SpecialFunctions = "0.10"
StatsFuns = "0.9"
SymPy = "1.0"
TransformVariables = "0.3"
julia = "^1.3"
