name = "Soss"
uuid = "8ce77f84-9b61-11e8-39ff-d17a774bf41c"
author = ["Chad Scherrer <chad.scherrer@gmail.com>"]
version = "0.19.0"

[deps]
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
CanonicalTraits = "a603d957-0e48-4f86-8fbd-0b7bc66df689"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
GeneralizedGenerated = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
IRTools = "7869d1d1-7146-5819-86e3-90919afe41df"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
MaskArrays = "0779ba27-d013-422b-b20d-67aa3361bf56"
MeasureTheory = "eadaa1a4-d27c-401d-8699-e962e1bbc33b"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
NestedTuples = "a734d2a7-8d68-409b-9419-626914d4061d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
SampleChains = "754583d1-7fc4-4dab-93b5-5eaca5c9622e"
SimpleGraphs = "55797a34-41de-5266-9ec1-32ac4eb504d3"
SimplePartitions = "ec83eff0-a5b5-5643-ae32-5cbf6eedec9d"
SimplePosets = "b2aef97b-4721-5af9-b440-0bad754dc5ba"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
SymbolicCodegen = "fc9b0551-4f1b-42e1-8440-e8a535f5a551"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
TransformVariables = "84d833dd-6860-57f9-a1a7-6da5db126cff"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[compat]
ArrayInterface = "3"
CanonicalTraits = "0.2"
DataStructures = "0.18"
DiffResults = "1"
FillArrays = "0.8, 0.9, 0.10, 0.11"
GeneralizedGenerated = "0.3"
Graphs = "0.10"
IRTools = "0.4"
IterTools = "1"
LazyArrays = "0.14, 0.15, 0.16, 0.17, 0.18,0.19,0.20,0.21"
MLStyle = "0.3,0.4"
MacroTools = "0.5"
MappedArrays = "0.3, 0.4"
MeasureTheory = "0.6,0.7"
NamedTupleTools = "0.12, 0.13"
NestedTuples = "0.3"
RecipesBase = "0.7,0.8, 1"
Reexport = "1"
Requires = "1"
RuntimeGeneratedFunctions = "0.5"
SampleChains = "0.3"
SimpleGraphs = "0.3, 0.4, 0.5, 0.6, 0.7"
SimplePartitions = "0.2, 0.3"
SimplePosets = "0.0, 0.1"
SpecialFunctions = "0.9, 0.10, 1"
StatsBase = "0.33"
StatsFuns = "0.9"
SymbolicCodegen = "0.2"
SymbolicUtils = "0.8, 0.9, 0.10"
TransformVariables = "0.3"
Tullio = "0.2"
julia = "1.5"

[extras]
BayesianLinearRegression = "5047281b-d44e-44a3-ad3e-58447b69b7ca"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["BayesianLinearRegression", "Documenter", "Literate", "Plots", "Random", "StableRNGs", "Test"]
